"""empty message

Revision ID: ca49a61076a7
Revises: 
Create Date: 2022-08-29 23:58:57.635832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca49a61076a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immobile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('toilets', sa.Integer(), nullable=True),
    sa.Column('suites', sa.Integer(), nullable=True),
    sa.Column('parking', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('furnished', sa.Boolean(), nullable=True),
    sa.Column('swimming_pool', sa.Boolean(), nullable=True),
    sa.Column('neighborhood', sa.Integer(), nullable=True),
    sa.Column('s_neighborhood', sa.String(), nullable=True),
    sa.Column('validate', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('correct_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('immobile')
    # ### end Alembic commands ###
